In [133]:
import numpy as np


In [134]:
''' BMP header fields
    uint16_t headerField;
    uint32_t fileSize;
    uint32_t imageOffset;
    // DIB header
    uint32_t headerSize;
    uint32_t imageWidth;
    uint32_t imageHeight;
    uint16_t colourPlanes;
    uint16_t bitsPerPixel;
    uint32_t compression;
    uint32_t imageSize;
    uint32_t xPixelsPerMeter;
    uint32_t yPixelsPerMeter;
    uint32_t totalColors;
    uint32_t importantColors;
'''
class BitmapHeader():
    

    

    def __init__(self, arr):
        # BMP header fields
        # fileType = np.ones(4,int)
        # fileSize = np.ones(4,int)
        # res1 = np.ones(2,int)
        # res2 = np.ones(2,int)
        # pixelDataOffSet = np.ones(4,int)
        
        self.fileType = arr[:4]
        self.fileSize = arr[4:8]
        self.res1 = arr[8:10]
        self.res2 = arr[10:12]
        self.pixelDataOffset = arr[12:16]
        self.header =[
            self.fileType,
            self.fileSize, 
            self.res1,
            self.res2,
            self.pixelDataOffset
        ]
        # DIB header
        # self.headerSize = np.ones(4,int)
        # self.imageWidth = np.ones(4,int)
        # imageHeight = np.ones(4,int)
        # colourPlanes = np.ones(2,int)
        # bitsPerPixel = np.ones(2,int)
        # compression = np.ones(4,int)
        # imageSize = np.ones(4,int)
        # xPixelsPerMeter = np.ones(4,int)
        # yPixelsPerMeter = np.ones(4,int)
        # totalColors = np.ones(4,int)
        # importantColors = np.ones(4,int)
        self.headerSize = arr[16:20]
        self.imageWidth = arr[20:24]
        self.imageHeight = arr[24:28]
        self.colorPlanes = arr[28:30]
        self.bitsPerPixel = arr[30:32]
        self.compression = arr[32:36]
        self.imageSize = arr[36:40]
        self.xPixelsPerMeter = arr[40:44]
        self.yPixelsPerMeter = arr[44:48]
        self.totalColors = arr[48:52]
        self.importantColors = arr[52:]
        
        self.dib=[
            self.headerSize, 
            self.imageWidth,
            self.imageHeight, 
            self.colorPlanes, 
            self.compression, 
            self.imageSize,
            self.xPixelsPerMeter, 
            self.yPixelsPerMeter, 
            self.totalColors,
            self.importantColors
        ]
    
    def get_header(self):
        print(self.header)

    def get_dib(self):
        print(self.dib)
        


In [135]:
import random
data = np.random.rand(56)
data


array([0.95479113, 0.81630631, 0.74451557, 0.47636985, 0.32711681,
       0.30831839, 0.23876651, 0.69195308, 0.89371229, 0.22165821,
       0.06237512, 0.89083694, 0.96724832, 0.63738417, 0.33533744,
       0.67673319, 0.83063276, 0.56353474, 0.47084199, 0.09230268,
       0.49275234, 0.11199142, 0.43665662, 0.78490356, 0.61769949,
       0.47034647, 0.75802494, 0.29681912, 0.12135726, 0.97858479,
       0.99897888, 0.59411149, 0.11810791, 0.29027905, 0.03605465,
       0.99087312, 0.23050531, 0.68468488, 0.61870059, 0.11602308,
       0.89944212, 0.15153566, 0.5239405 , 0.77067056, 0.61371352,
       0.93763742, 0.73625062, 0.93986317, 0.08530369, 0.04999106,
       0.23744197, 0.70159582, 0.13050971, 0.04835193, 0.60854301,
       0.06777326])

In [136]:
data[:16]

array([0.95479113, 0.81630631, 0.74451557, 0.47636985, 0.32711681,
       0.30831839, 0.23876651, 0.69195308, 0.89371229, 0.22165821,
       0.06237512, 0.89083694, 0.96724832, 0.63738417, 0.33533744,
       0.67673319])

In [137]:
data[16:]

array([0.83063276, 0.56353474, 0.47084199, 0.09230268, 0.49275234,
       0.11199142, 0.43665662, 0.78490356, 0.61769949, 0.47034647,
       0.75802494, 0.29681912, 0.12135726, 0.97858479, 0.99897888,
       0.59411149, 0.11810791, 0.29027905, 0.03605465, 0.99087312,
       0.23050531, 0.68468488, 0.61870059, 0.11602308, 0.89944212,
       0.15153566, 0.5239405 , 0.77067056, 0.61371352, 0.93763742,
       0.73625062, 0.93986317, 0.08530369, 0.04999106, 0.23744197,
       0.70159582, 0.13050971, 0.04835193, 0.60854301, 0.06777326])

In [138]:
bmp = BitmapHeader(data)
bmp.get_header()

[array([0.95479113, 0.81630631, 0.74451557, 0.47636985]), array([0.32711681, 0.30831839, 0.23876651, 0.69195308]), array([0.89371229, 0.22165821]), array([0.06237512, 0.89083694]), array([0.96724832, 0.63738417, 0.33533744, 0.67673319])]


In [139]:
bmp.get_dib()

[array([0.83063276, 0.56353474, 0.47084199, 0.09230268]), array([0.49275234, 0.11199142, 0.43665662, 0.78490356]), array([0.61769949, 0.47034647, 0.75802494, 0.29681912]), array([0.12135726, 0.97858479]), array([0.11810791, 0.29027905, 0.03605465, 0.99087312]), array([0.23050531, 0.68468488, 0.61870059, 0.11602308]), array([0.89944212, 0.15153566, 0.5239405 , 0.77067056]), array([0.61371352, 0.93763742, 0.73625062, 0.93986317]), array([0.08530369, 0.04999106, 0.23744197, 0.70159582]), array([0.13050971, 0.04835193, 0.60854301, 0.06777326])]
