In [83]:
import numpy as np

In [84]:
class Fib_mat():
    '''
    input : u,v
    create matrix [[v-u,u],[v,v+u] = [[a,b],[d,c]
    sides c1 = a*d, c2 = 2*b*c, c3 = a*c+b*d
    '''    
    def __init__(self,u,v):
        self.a = v-u
        self.b = u
        self.c = v
        self.d = v+u
        self.m = np.matrix([[self.a,self.b],[self.d,self.c]])
        self.c1 = self.a*self.d
        self.c2 = 2*self.b*self.c
        self.c3 = self.a*self.c+self.b*self.d
  
    def __repr__(self):
        return f'{self.c1} {self.c2} {self.c3}'
    
    def children(self):
        self.center = Fib_mat(self.c,self.d+self.c)
        self.left = Fib_mat(self.b,self.d+self.b)
        self.right = Fib_mat(self.c,self.c+self.a)
        
        
    def check(self):
        return self.c1**2+self.c2**2==self.c3**2

In [85]:
help(Fib_mat)

Help on class Fib_mat in module __main__:

class Fib_mat(builtins.object)
 |  Fib_mat(u, v)
 |  
 |  input : u,v
 |  create matrix [[v-u,u],[v,v+u] = [[a,b],[d,c]
 |  sides c1 = a*d, c2 = 2*b*c, c3 = a*c+b*d
 |  
 |  Methods defined here:
 |  
 |  __init__(self, u, v)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  check(self)
 |  
 |  children(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [86]:
# 1 1 2 3 5 8 13 21 ...

m = Fib_mat(1,2)
m,m.check()

(3 4 5, True)

In [87]:
m.children()


In [88]:
m.m,m.left.m,m.center.m, m.right.m

(matrix([[1, 1],
         [3, 2]]),
 matrix([[3, 1],
         [5, 4]]),
 matrix([[3, 2],
         [7, 5]]),
 matrix([[1, 2],
         [5, 3]]))

In [89]:
m.left.c1,m.left.c2,m.left.c3,m.left.check()

(15, 8, 17, True)

In [90]:
m.center.c1,m.center.c2,m.center.c3,m.center.check()

(21, 20, 29, True)

In [91]:
m.right.c1,m.right.c2,m.right.c3,m.right.check()

(5, 12, 13, True)