In [65]:
import numpy as np

a=np.mat('[1 2 4 ; 3 4 5. ; 0 4 2]')
b=np.mat('[2. ; 4 ; 6]')
a

matrix([[1., 2., 4.],
        [3., 4., 5.],
        [0., 4., 2.]])

In [80]:
a=np.mat('[1 2 4 ; 3 4 5. ; 0 4 2]')
d1 = -a[1,0]/a[0,0]
a[1,:]=[a[0,0]*d1+a[1,0], a[0,1]*d1+a[1,1], a[0,2]*d1+a[1,2]]
a
d2 = -a[2,1]/a[1,1]
a[2,:]=[a[1,0]*d2+a[2,0], a[1,1]*d2+a[2,1], a[1,2]*d2+a[2,2]]
a

matrix([[  1.,   2.,   4.],
        [  0.,  -2.,  -7.],
        [  0.,   0., -12.]])

In [83]:
a=np.mat('[1 2 4 ; 3 4 5. ; 0 4 2]')
d1 = -a[1,0]/a[0,0]
e1 = np.mat('[1 0 0 ; 0 1 0 ; 0 0 1]')
e1[1,0]=d1
e1

matrix([[ 1,  0,  0],
        [-3,  1,  0],
        [ 0,  0,  1]])

In [84]:
a = e1*a
a

matrix([[ 1.,  2.,  4.],
        [ 0., -2., -7.],
        [ 0.,  4.,  2.]])

In [85]:
d2 = -a[2,1]/a[1,1]
a[2,:]=[a[1,0]*d2+a[2,0], a[1,1]*d2+a[2,1], a[1,2]*d2+a[2,2]]
e2 = np.mat('[1 0 0 ; 0 1 0 ; 0 0 1]')
e2[2,1]=d2
e2

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 2, 1]])

In [86]:
a=np.mat('[1 2 4 ; 3 4 5. ; 0 4 2]')
e1*a

matrix([[ 1.,  2.,  4.],
        [ 0., -2., -7.],
        [ 0.,  4.,  2.]])

In [87]:
e2*e1*a

matrix([[  1.,   2.,   4.],
        [  0.,  -2.,  -7.],
        [  0.,   0., -12.]])

In [88]:
e2*e1

matrix([[ 1,  0,  0],
        [-3,  1,  0],
        [-6,  2,  1]])

In [91]:
 a = np.matrix('1 2; 3 4')

In [92]:
a


matrix([[1, 2],
        [3, 4]])

In [93]:
b=np.mat('1 2 4 ; 3 4 5. ; 0 4 2')

In [94]:
b


matrix([[1., 2., 4.],
        [3., 4., 5.],
        [0., 4., 2.]])

In [95]:
b.T


matrix([[1., 3., 0.],
        [2., 4., 4.],
        [4., 5., 2.]])

In [96]:
b.H

matrix([[1., 3., 0.],
        [2., 4., 4.],
        [4., 5., 2.]])

In [98]:
b2=b.I

In [99]:
b2*b


matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [100]:
# import sympy 
from sympy import *

M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) 
print("Matrix : {} ".format(M)) 

# Use sympy.rref() method 
M_rref = M.rref() 
	
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref)) 


Matrix : Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0,   1,   3],
[0, 1, 2/3, 1/3],
[0, 0,   0,   0]]), (0, 1))


In [101]:
M = Matrix([[14, 0, 11, 3], [22, 23, 4, 7], [-12, -34, -3, -4]]) 
print("Matrix : {} ".format(M)) 

# Use sympy.rref() method 
M_rref = M.rref() 
	
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref)) 


Matrix : Matrix([[14, 0, 11, 3], [22, 23, 4, 7], [-12, -34, -3, -4]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0, 1405/4254],
[0, 1, 0,    10/709],
[0, 0, 1, -314/2127]]), (0, 1, 2))


In [105]:
M = Matrix([[1,2,4 ],[ 3 ,4 ,5. ],[ 0 ,4 ,2]])
print("Matrix : {} ".format(M)) 

# Use sympy.rref() method 
M_rref = M.rref() 
	
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref)) 


Matrix : Matrix([[1, 2, 4], [3, 4, 5.00000000000000], [0, 4, 2]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))
