In [88]:
# https://realpython.com/python-scipy-cluster-optimize/

from pathlib import Path
import numpy as np
from scipy.cluster.vq import whiten, kmeans, vq
dir = Path(Path.home(),"Documents/Python/jupyter_notebooks")
dir

PosixPath('/home/jean/Documents/Python/jupyter_notebooks')

In [89]:
data = Path(dir,"SMSSpamCollection.csv").read_text()
#data = data.strip()
#data

data = data.split("\n")
#data=data[:10]
data

['v1,v2,,,',
 'ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,',
 'ham,Ok lar... Joking wif u oni...,,,',
 "spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,",
 'ham,U dun say so early hor... U c already then say...,,,',
 'ham,"Nah I don\'t think he goes to usf, he lives around here though",,,',
 'spam,"FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, 1.50 to rcv",,,',
 'ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,',
 "ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,",
 'spam,WINNER!! As a valued network customer you have been selected to receivea 900 prize r

In [90]:
digit_counts = np.empty((len(data), 2), dtype=int)
digit_counts

array([[    139708926714800,      94387115062960],
       [     94387113611520,      94387115062960],
       [8247620858625028008,                   0],
       ...,
       [  29555010000584814,   28992060047229036],
       [  27303540894466159,   32651234744008811],
       [  28429466576289896,   28429462281322528]])

In [91]:
for i, line in enumerate(data):
    print(i,line)
    case, message = line.split(",",1)

    num_digits = sum(c.isdigit() for c in message)
    digit_counts[i, 0] = 0 if case == "ham" else 1
    digit_counts[i, 1] = num_digits

0 v1,v2,,,
1 ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,
2 ham,Ok lar... Joking wif u oni...,,,
3 spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,
4 ham,U dun say so early hor... U c already then say...,,,
5 ham,"Nah I don't think he goes to usf, he lives around here though",,,
6 spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, 1.50 to rcv",,,
7 ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,
8 ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,
9 spam,WINNER!! As a valued network customer you have been selected to receivea 900 prize reward! To claim call 0

In [92]:
digit_counts

array([[1, 1],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [93]:
unique_counts = np.unique(digit_counts[:, 1], return_counts=True)
unique_counts

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 40, 41, 47]),
 array([4110,  487,  160,   78,   42,   39,   16,   14,   28,   17,   16,
          34,   30,   31,   37,   29,   35,   33,   41,   47,   18,   31,
          28,   36,   34,   16,   16,   13,   19,    9,    2,    6,    3,
           4,    3,    4,    1,    1,    4,    2,    1]))

In [94]:
unique_counts = np.transpose(np.vstack(unique_counts))

In [95]:
unique_counts

array([[   0, 4110],
       [   1,  487],
       [   2,  160],
       [   3,   78],
       [   4,   42],
       [   5,   39],
       [   6,   16],
       [   7,   14],
       [   8,   28],
       [   9,   17],
       [  10,   16],
       [  11,   34],
       [  12,   30],
       [  13,   31],
       [  14,   37],
       [  15,   29],
       [  16,   35],
       [  17,   33],
       [  18,   41],
       [  19,   47],
       [  20,   18],
       [  21,   31],
       [  22,   28],
       [  23,   36],
       [  24,   34],
       [  25,   16],
       [  26,   16],
       [  27,   13],
       [  28,   19],
       [  29,    9],
       [  30,    2],
       [  31,    6],
       [  32,    3],
       [  33,    4],
       [  34,    3],
       [  35,    4],
       [  36,    1],
       [  37,    1],
       [  40,    4],
       [  41,    2],
       [  47,    1]])

In [96]:
whitened_counts = whiten(unique_counts)
whitened_counts

array([[0.00000000e+00, 6.49350487e+00],
       [8.11755468e-02, 7.69425030e-01],
       [1.62351094e-01, 2.52788511e-01],
       [2.43526640e-01, 1.23234399e-01],
       [3.24702187e-01, 6.63569841e-02],
       [4.05877734e-01, 6.16171995e-02],
       [4.87053281e-01, 2.52788511e-02],
       [5.68228827e-01, 2.21189947e-02],
       [6.49404374e-01, 4.42379894e-02],
       [7.30579921e-01, 2.68587793e-02],
       [8.11755468e-01, 2.52788511e-02],
       [8.92931014e-01, 5.37175586e-02],
       [9.74106561e-01, 4.73978458e-02],
       [1.05528211e+00, 4.89777740e-02],
       [1.13645765e+00, 5.84573432e-02],
       [1.21763320e+00, 4.58179176e-02],
       [1.29880875e+00, 5.52974868e-02],
       [1.37998430e+00, 5.21376304e-02],
       [1.46115984e+00, 6.47770559e-02],
       [1.54233539e+00, 7.42566251e-02],
       [1.62351094e+00, 2.84387075e-02],
       [1.70468648e+00, 4.89777740e-02],
       [1.78586203e+00, 4.42379894e-02],
       [1.86703758e+00, 5.68774150e-02],
       [1.948213

In [97]:
codebook, _ = kmeans(whitened_counts, 3)
codebook

array([[0.        , 6.49350487],
       [0.85234324, 0.09732358],
       [2.52050073, 0.01840616]])

In [98]:
codes, _ = vq(unique_counts, codebook)
codes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      dtype=int32)

In [99]:
print(unique_counts[codes == 0][-1])

[28 19]


In [100]:
print(unique_counts[codes == 1][-1])

IndexError: index -1 is out of bounds for axis 0 with size 0

In [ ]:
print(unique_counts[codes == 2][-1])